/**
 * lib/supabase/types.ts — Database type stub.
 * This file is generated by `supabase gen types typescript --local`.
 * Once Supabase is linked and the first migration is applied, run:
 *   pnpm supabase gen types typescript --local > src/lib/supabase/types.ts
 * and commit the result.
 *
 * Placeholder until then — do not hand-write this file.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// TODO: replace with generated types after first migration
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
